### ISSUE TITLE
A quick question about classifying MERFISH

### ISSUE THREAD

**Issue by HelloWorldLTY** [nitzanlab/Annotatability#2]
Hi, thanks for your great work! I have a very naive question about using Annotatibility in MERFISH data. I think you did not use location information in training the neural network, but it seems that the prediction result is also reliable. Does this imply that the spatial information might not be very contributive in this task? Thanks.

Also, if I have a new dataset without anntation, do you have any recommendations about how to apply Annotatibility in my own dataset? Thanks.

**Comment by JonathanKarin** [comment]
Thank you for your kind words and insightful questions!

Regarding the use of spatial information, we did not incorporate spatial data in our analysis. However, this does not imply that spatial information is not contributive to the task of cell type annotation. In many cases, spatial information can significantly enhance annotation efforts, but exploring this aspect was beyond the scope of our paper.

For your dataset without existing annotations, Annotatibility requires an initial annotation. You can start with a basic or naive annotation of your data and then applying Annotatibility to refine and improve it, as we demonstrated in the EMT section of our manuscript.

Best regards,

Jonathan
